server:
  port: 3763
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.108:8848

feign:
  httpclient:
    enabled: false
    # feign最大连接数
    maxConnections: 10
    max-connections-per-route: 50
    # 线程存活时间
    time-to-live: 900
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

hystrix:
  threadpool:
    default:
      coreSize: 20
  command:
    default:
      execution:
        timeout:
          enabled: true